FROM ubuntu:16.04

RUN apt-get -y update

# PYTHON DEPENDENCIES
RUN apt-get install -y build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

# PYTHON
RUN apt-get install -y python2.7 python2.7-dev python3.5 python3.5-dev libgcc-4.8-dev  libgcc-5-dev python python-pip git python-nose
